package com.amaret.pollen.parser;

public enum Flags {
	CLASS, COMPOSITION, CONST, CONSTRUCTOR, ENUM, ERR, 
	FIELD, INTRINSIC_VAR, HOST, 
	IS_POSTEXPR, IS_THISPTR, IS_PTR, IS_DECL, IS_TYPEDEF, // these are for codegen
	LOG, META, META_ARG, TYPE_META_ARG, 
	METHOD, MODULE, NEW, OUT,
	PRESET, PROTOCOL, PROTOCOL_MEMBER, PUBLIC,
	VOLATILE, VOID_FCN, VOID_INSTANCE
}
