package com.amaret.pollen.parser;

public enum Flags {
	CLASS, COMPOSITION, CONST, CONSTRUCTOR, ENUM, ERR, 
	FIELD, FCNREF, INTRINSIC_VAR, HOST, LOG, 
	META, META_ARG, TYPE_META_ARG, 
	METHOD, MODULE, NEW, OUT,
	PROTOCOL, PROTOCOL_MEMBER, PUBLIC,
	VOLATILE, VOID_FCN, VOID_INSTANCE
}
